# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'HelloWorld', :path => '../HelloWorld.podspec', :configurations => 'Debug'
#  script_phase :name => 'Pack Framework', :script => 'ruby ${SRCROOT}/../carthage_pack.rb'
#  script_phase :name => 'Pack Framework', :script => 'sh ${SRCROOT}/../cocoapackager_pack.sh'
  script_phase :name => 'Pack Framework', :script => 'sh ${SRCROOT}/../xcodebuild_pack.sh'
  
end
